services:
  frontend:
    build: ./
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - AUTH_SECRET="aaZqtZiI6dmgWn6IgZO39I3vPXmf75nJWdFQni4p0Rs="
      - AUTH_GOOGLE_ID=363106468911-tbvl5p2ugd89c6jrbr7266vfcptglb2p.apps.googleusercontent.com
      - AUTH_GOOGLE_SECRET=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
      - MONGO=mongodb+srv://ahmedomaralfarouq:JsRG27ZaIt1nppwf@finvestorcluter.wyr0s.mongodb.net/users?retryWrites=true&w=majority&appName=finvestorCluter
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./
          target: app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
